[workspace]
members = [
    "epgi-core",
    "epgi-common",
    "epgi-futures",
    "epgi-2d",
    "epgi-glazier",
    "examples/*",
]
resolver = "2"


[workspace.package]
edition = "2021"
rust-version = "1.70"
keywords = ["graphics"]
license = "MIT OR Apache-2.0"

[workspace.dependencies.epgi-core]
package = "epgi-core"
path = "./epgi-core"

[workspace.dependencies.epgi-2d]
package = "epgi-2d"
path = "./epgi-2d"

[workspace.dependencies.epgi-common]
package = "epgi-common"
path = "./epgi-common"

[workspace.dependencies.epgi-glazier]
package = "epgi-glazier"
path = "./epgi-glazier"


[workspace.dependencies]
vello = { git = "https://github.com/linebender/vello", rev = "9d7c4f00d8db420337706771a37937e9025e089c" }
vello_encoding = { git = "https://github.com/linebender/vello", rev = "9d7c4f00d8db420337706771a37937e9025e089c" }
peniko = { git = "https://github.com/linebender/peniko", rev = "cafdac9a211a0fb2fec5656bd663d1ac770bcc81" }
parley = { git = "https://github.com/dfrg/parley", rev = "2371bf4b702ec91edee2d58ffb2d432539580e1e" }
glazier = { git = "https://github.com/linebender/glazier", rev = "19a01ba8a97f15bf499ac64e6ea9690d7390deb5", default-features = false, features = [
    "accesskit",
    "x11",
] }
accesskit = "0.11"
wgpu = "0.17"
rayon = "1.7"
